# .github/workflows/go.yaml

on: push
name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout 代码
      - uses: actions/setup-go@v3 # 配置 Go 环境
        with:
          go-version: "1.18" # 改成自己的版本

      - run: make linux
      - run: make windows

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            bin/linux_x64_86
            bin/windows_x64-86.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}