name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Building Linux
      run: make linux
      
    - name: Building Windows
      run: make windows

    - name: Release
      uses: softprops/action-gh-release@v1
      with: # 将下述可执行文件 release 上去
        files: |
          bin/linux_x64-86
          bin/windows_x64-86.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
